version: '3.7'

services:
    rocket.chat:
      image: rocket.chat:latest
      restart: always
      container_name: rocket.chat
      ports:
        - "91:3000"
      environment:
        MONGO_OPLOG_URL: mongodb://root:123456@192.168.3.205:27017/local?authSource=admin
        MONGO_URL: mongodb://root:123456@192.168.3.205:27017/chat1?authSource=admin
        ROOT_URL: http://192.168.3.205:3000
        HTTP_PROXY: 192.168.3.205
        HTTPS_PROXY: 192.168.3.205
      privileged: true



      # - ./uploads:/app/uploads