name: docs

on:
  # 每当 push 到 main 分支时触发部署
  push:
    branches: [main]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run docs:build
      - name: 部署到 catpd.cn
        uses: wlixcc/SFTP-Deploy-Action@v1.2.6
        with:
          username: 'root'
          server: 'catpd.cn'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: 'docs/.vuepress/dist/*'
          remote_path: '/root/ddstudy/dist'
          sftpArgs: '-o ConnectTimeout=5'
